name: Add Asset
on:
  workflow_dispatch:
    inputs:
      osmosis_zone:
        description: 'Osmosis Zone'
        required: true
        default: 'osmosis (osmosis-1)'
        options: 
          - 'osmosis (osmosis-1)'
          - 'osmosistestnet5 (osmo-test-5)'
          - 'osmosistestnet (osmo-test-4)'
      chain_name:
        description: 'chain_name (Chain Registry directory)'
        required: true
        default: 'cosmoshub'
      base_denom:
        description: 'base_denom (Asset base)'
        required: true
        default: 'uatom'
      path:
        description: 'path (IBC transfer path--required for all IBC transferred assets)'
        required: false
        default: 'transfer/channel-141/uatom'
      osmosis_main:
        description: 'osmosis_main (whether to appear as verified asset--default to FALSE)'
        required: false
        type: boolean
        default: false
      osmosis_pool:
        description: 'Pool ID of any on-chain liquidity pool containing the asset if liquidity has been added. '
        required: false
      request_staging_frontend:
        description: 'If liquidity not yet been added, you can request a Staging Frontend to add liquidity'
        required: false
        type: boolean
        default: false


jobs:
  add_asset:
    name: Add Asset
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Git Sumbodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
      
      - name: Set environment variables
        run: |
          echo "osmosis_zone=${{ github.event.inputs.osmosis_zone }}" >> $GITHUB_ENV
          echo "chain_name=${{ github.event.inputs.chain_name }}" >> $GITHUB_ENV
          echo "base_denom=${{ github.event.inputs.base_denom }}" >> $GITHUB_ENV
          echo "path=${{ github.event.inputs.path }}" >> $GITHUB_ENV
          echo "osmosis_main=${{ github.event.inputs.osmosis_main }}" >> $GITHUB_ENV
          echo "osmosis_pool=${{ github.event.inputs.osmosis_pool }}" >> $GITHUB_ENV
          echo "request_staging_frontend=${{ github.event.inputs.request_staging_frontend }}" >> $GITHUB_ENV

      - name: Run validation script
        working-directory: ./.github/workflows/utility
        run: node validate_add_asset.mjs
          
      - name: Add Commit Push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[AUTO]"
          commit_message: "Add Zone Asset"
          force: false
          target_branch: update/add_asset
      
      - name: Create A PR
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update/add_asset
          target_branch: main
          title: Add Zone Asset
          body: |
            **Automated pull request**
            osmosis_zone = ${{ github.event.inputs.osmosis_zone }}
            chain_name = ${{ github.event.inputs.chain_name }}
            base_denom = ${{ github.event.inputs.base_denom }}
            path = ${{ github.event.inputs.path }}
            osmosis_main = ${{ github.event.inputs.osmosis_main }}
            osmosis_pool = ${{ github.event.inputs.osmosis_pool }}
            request_staging_frontend = ${{ github.event.inputs.request_staging_frontend }}
          old_string: "**THIS IS AN AUTOMATED ADDITON OF ASSET**"
          new_string: "** ADD ASSET - ${{ github.event.inputs.chain_name }}::${{ github.event.inputs.base_denom }}**"
          get_diff: true
          ignore_users: "dependabot"
