on: [workflow_dispatch]
name: Localization Post
jobs:
  generate_zone_config:
    name: Localization Post
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0

      - name: Install dependencies
        run: npm install

      - name: Run post-localization code
        working-directory: ./.github/workflows/utility
        run: node localization_post.mjs
      
      - name: Add Commit Push
        run: |
          git add .
          git commit -m "$localization post processing Update"
          git push origin update/localization_post
      
      - name: Create A PR
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update/localization_post
          target_branch: main
          title: localization post Update
          body: "**Automated pull request**"
          old_string: "**THIS IS AN AUTOMATED POST PROCESSING OF LOCALIZATION**"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
