name: Client Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Setup Golang
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.19
      -
        name: Display go version
        run: go version
      -
        name: Run unit tests
        run: cd client/go && go test ./...