# Description: Validates osmosis.zone_chains.json against schema on pull requests
# Included in: NOT included in Generate All Files bundle (PR validation only)
# Trigger: Automatically runs on pull requests to main branch
# Output: Pass/fail validation status for PR checks

on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_zone_chains:
    name: Validate zone chains
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate Zone Chains schema
        run: |
          for file in $(find . -name 'osmosis.zone_chains.json'); do
            if ! jsonschema -i "$file" ./zone_chains.schema.json; then
              exit 1
            fi
          done
